#config_version=5
mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        anchor_x: right
        anchor_y: bottom
        x: left+650
        y: 850
      - type: text
        text: PLAYER (number)
        y: 30%
        x: 65%
        font_size: 50
      - type: text
        text: BALL (ball)
        y: 25%
        x: 65%
        font_size: 50
      - type: text
        text: 'Left Flipper Flips: (left_flipper_flips)'
        y: 50%
        x: 65%
        color: blue
        font_size: 50
      - type: text
        text: 'Right Inlane Hits: (right_inlane_hits)'
        y: 40%
        x: 65%
        color: red
        font_size: 50
      - type: image
        #image: labyrinth_backglass # video size is width: 1200 height: 800
        image: labyrinth_backglass-v2

shots:
  my_first_shot:
    switch: s_right_inlane  # pick a switch that's valid in your machine
    show_tokens:
      lights: l_led1 # pick an LED that's valid in your machine
    profile: my_first_profile

variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  # s_right_inlane_active:
  #   score: 100
  #   right_inlane_hits: 1
  # my_first_shot_hit:
  #   score: 100
  #   right_inlane_hits: 1
  s_left_flipper_active:
    score: 1000
    left_flipper_flips: 1
  s_spinner_left_active:
    score: 10000

shot_profiles:
  my_first_profile:
    states:
      - name: unlit  # step 1
        show: off
      - name: flashing  # step 2
        show: flash
      - name: lit  # step 3
        show: on
    loop: true