#config_version=5

hardware:
  platform: fast

fast:
  driverboards: fast
  ports: /dev/tty.usbserial-00003014B, /dev/tty.usbserial-00003014C
  watchdog: 1000
  debug: true

switches:
  s_left_flipper:
    number: 0-0
    tags: left_flipper
  s_right_flipper:
    number: 0-1
    tags: right_flipper

coils:
  c_flipper_left:
    number: 0-0
    allow_enable: true
    default_pulse_ms: 12
    default_pulse_power: 1
    default_hold_power: 0.45
  c_flipper_right:
    number: 0-1
    allow_enable: true
    default_pulse_ms: 12
    default_pulse_power: 1
    default_hold_power: 0.45

playfields:
  playfield:
    tags: default
    default_source_device: None #use none in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3 # needed until we create start button and all that

  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3 # needed until we create start button and all that
