#config_version=5

hardware:
  platform: fast

fast:
  driverboards: fast
  ports: /dev/tty.usbserial-00002014B, /dev/tty.usbserial-00002014C
  watchdog: 1000
  # debug: true

switches:
  s_left_flipper:
    number: 0-0
    tags: left_flipper
  s_right_flipper:
    number: 0-1
    tags: right_flipper
  # s_start:
  #   number: 0-2
  #   tags: start
  s_start:
    number: 0-12
    tags: start
  s_spinner_left:
    number: 0-2
  s_trough1:
    number: 0-3
    type: NC
  s_trough2:
    number: 0-4
    type: NC
  s_trough3:
    number: 0-5
    type: NC
  s_trough4:
    number: 0-6
    type: NC
  s_trough5:
    number: 0-7
    type: NC
  s_trough6:
    number: 0-8
    type: NC
  s_trough_jam:
    number: 0-9
    type: NC
  s_plunger:
    number: 0-10
  s_right_inlane:
    number: 0-11
    # tags: playfield_active

coils:
  c_flipper_left:
    number: 0-0
    allow_enable: true
    default_pulse_ms: 12
    default_pulse_power: 1
    default_hold_power: 0.45
  c_flipper_right:
    number: 0-1
    allow_enable: true
    default_pulse_ms: 12
    default_pulse_power: 1
    default_hold_power: 0.45
  c_trough_eject:
    number: 0-2
    default_pulse_ms: 20

ball_devices:
  bd_trough:
    # ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    ball_switches: s_trough1, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    # eject_timeouts: 3s
    debug: true
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
    # eject_timeouts: 5s
  
playfields:
  playfield:
    tags: default
    # default_source_device: None #use none in steps before 8
    default_source_device: bd_plunger


virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_left_flipper
    #enable_events: machine_reset_phase_3 # needed until we create start button and all that

  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_right_flipper
    #enable_events: machine_reset_phase_3 # needed until we create start button and all that

displays:
  window:
    # width: 1404
    # height: 1040
    width: 1872
    height: 1386

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60

  # start segement displays https://docs.missionpinball.org/en/latest/displays/display/alpha_numeric.html
  segment_displays:
    widgets:
      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        font_name: ten_segment
        color: blue
        x: 620
        y: 724
        font_size: 240
        anchor_x: right
        anchor_y: bottom
        z: 2
  # end segment displays

slide_player:
  init_done: welcome_slide
  game_started: segment_displays

keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  p:
    switch: s_plunger
    toggle: true
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  6:
    switch: s_trough6
    toggle: true
  n:
    event: mode2_start
  m:
    event: mode2_stop

assets:
  sounds:
    breakloop:
      volume: 1.0
      priority: 100
    rezzo:
      volume: 1.0
      priority: 100

videos:
  trailer_video:
    # width: 100
    # height: 70
    file: trailer.mp4
    # file: trailer_hd.mp4
    # file: trailer_hd_nosound.mp4

sound_player:
  mode_attract_started:
    breakloop:
      action: play
      loops: -1
  mode_attract_stopped:
    breakloop:
      action: stop
  mode_base_started:
    rezzo:
      action: play

modes:
  - base
  - attract
  - mode2
  # - skillshot
  # - both_ramps_made
  # - multiball
  # - some_mode

player_vars:
  right_inlane_hits:
    initial_value: 0
  left_flipper_flips:
    initial_value: 0

lights:
  l_drop1:
    number:
    tags: drops
  l_drop2:
    number:
    tags: drops
  l_led1:
    number:
  l_led2:
    number:
  l_led3:
    number: